version: "3"
services:
  node-app:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - ./:/app:ro
      - ./app/node_modules
    #environment:
    #  - PORT=2000
    env_file:
      - ./.env