version: "3"
services:
  node-app:
    build: .
    ports:
      - "2000:2000"
    env_file:
      - ./.env
    depends_on:
      - mongo-db
      - redis-db
  mongo-db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kala
      - MONGO_INITDB_ROOT_PASSWORD=pw
    volumes:
      - mongodb:/data/db
  redis-db:
    image: redis
volumes:
  mongodb: